### ISSUE TITLE
World Of Fish

### ISSUE THREAD

**Issue by eternalxlks** [Brunozhon/Brunozhon.github.io#110]
I Copyrighted the name and idea of World War Fish, You copied it without my permission and even more, you didn't credit me!
I put your game on my website, but I credited you! You did nothing!

**Comment by Brunozhon** [comment]
1. I also credited you twice, [here](https://codepen.io/Brunozhon/details/WNVKmgB) and [here](https://brunozhon.github.io/#my-projects).
2. According to [this website](https://www.samvanderwielen.com/stealing-content-vs-inspiration/?srsltid=AfmBOorrsStyjb64GRrfo3ytT4ApAYTBN0deHFdHjI98iQdEavI5eEyG), mimicking other's creations, while annoying, is not illegal.
